builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
universal_binaries:
- replace: true
  hooks:
    post:
      - cmd: ./sign.sh {{ .Path }}
        output: true
release:
  github:
  draft: true
  replace_existing_draft: true
  mode: replace
